server:
  port: ${SERVER_PORT:8080}
  context-path: /
spring:
  profiles:
    active: ${SPRING_PROFILE:dev}
  datasource:
    url: ${PERSISTENCE_URL:jdbc:postgresql://store-hulk.cipvrppyh2ee.us-east-1.rds.amazonaws.com/store_hulk}
    username: ${PERSISTENCE_USER:postgres}
    password: ${PERSISTENCE_PASSWORD:12345678}
    type: com.zaxxer.hikari.HikariDataSource

    hikari:
      maximum-pool-size: 10
      idle-timeout: 90000
      minimum-idle: 2
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  http:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
springdoc:
  version: '@springdoc.version@'
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html